export const SCREEN_NAME = {
  HOME: 'Home',
  LOGIN: 'Login',
  REGISTER: 'Register',
  FORGOT_PASSWORD: 'ForgotPassword',
  SPLASH: 'Splash',
  ONBOARDING: 'Onboarding',
  UPDATE_INFO: 'UpdateInfo',
  TABS: 'Tabs',
  HOME_TAB: 'HomeTab',
  CELEBRATE_TAB: 'CelebrateTab',
  CELEBRATE: 'Celebrate',
  SETTING_TAB: 'SettingTab',
  SETTING: 'Setting',
  SPENDING_TAB: 'SpendingTab',
  SPENDING: 'Spending',
  BUDGET_TAB: 'BudgetTab',
  BUDGET: 'Budget',
  PAYMENT_DETAIL: 'PaymentDetail',
  TRIP_SETTLEMENT_DETAIL: 'TripSettlementDetail',
  TRIP_DETAIL: 'TripDetailScreen',
  ADD_EXPENSE: 'AddExpense',
  ADD_TRIP: 'AddTrip',
};
