-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('TRIP_INVITE', 'MEMBER_JOINED', 'EXPENSE_CREATED', 'BUDGET_WARNING', 'SETTLEMENT_REMINDER', 'EXPENSE_REMINDER', 'PAYMENT_MARKED', 'PAYMENT_CONFIRMED', 'INVITATION_REJECTED') NOT NULL;
