name: Deploy Backend to Heroku

on:
  push:
    branches:
      - master
    paths:
      - 'BackEnd/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cài Heroku CLI
      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      # Login Heroku
      - name: Login Heroku
        run: |
          echo "${{ secrets.HEROKU_API_KEY }}" | heroku auth:token

      # Deploy bằng git push
      - name: Deploy to Heroku
        run: |
          cd BackEnd/go-together-server
          git init
          git add .
          git commit -m "deploy"

          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
          git push heroku HEAD:master --force